target("dosemu-freedos")
    set_kind("phony")
    on_install(function (target)
        local installdir = target:installdir()
        local bindir = path.join(installdir, "bin")
        local libexecdir = path.join(installdir, "libexec", "dosemu")
        os.cp("$(projectdir)/src/dosemu-installdos", libexecdir)
        os.cp("$(projectdir)/src/dosemu-installmsdos",  libexecdir)
        os.cp("$(projectdir)/src/dosemu-installopendos",  libexecdir)
        os.cp("$(projectdir)/src/dosemu-install3rdpartydos",  bindir)
    end)
    on_uninstall(function (target)
        local installdir = target:installdir()
        local bindir = path.join(installdir, "bin")
        local libexecdir = path.join(installdir, "libexec", "dosemu")
        os.rm(path.join(libexecdir, "dosemu-installdos"))
        os.rm(path.join(libexecdir, "dosemu-installmsdos"))
        os.rm(path.join(libexecdir, "dosemu-installopendos"))
        os.rm(path.join(bindir, "dosemu-install3rdpartydos"))
    end)
